# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 2.2.0
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 前端地址
  #uiUrl: http://192.168.0.3
  uiUrl: http://dev.cacpaper.com:7779
  # 初始化密码
  initPassword: '000000'
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  #profile: H:/ruoyi/uploadPath
  profile: /deploy/oaaccount/upload
  # 获取ip地址开关
  addressEnabled: true

# baiduAPI发票识别配置
baiduapi:
  # 获取token地址
  authHost: https://aip.baidubce.com/oauth/2.0/token?
  # 官网获取的发票识别的 API Key
  apiKey: x0Tw65rE41bEK4OkvTCzwbU6
  # 官网获取的发票识别的 Secret Key
  secretKey: xoUGHuF1WsD2wdHsPBWfGtGYcFK6b21m
  # 识别增值税发票地址URL
  invoiceUrl: https://aip.baidubce.com/rest/2.0/ocr/v1/vat_invoice
  # 识别定额发票地址URL
  quotaInvoiceUrl: https://aip.baidubce.com/rest/2.0/ocr/v1/quota_invoice
  # 识别火车票地址URL
  trainTicketUrl: https://aip.baidubce.com/rest/2.0/ocr/v1/train_ticket
  # 识别机票行程单地址URL
  airTicketUrl: https://aip.baidubce.com/rest/2.0/ocr/v1/air_ticket
  # 识别出租票地址URL
  taxiTicketUrl: https://aip.baidubce.com/rest/2.0/ocr/v1/taxi_receipt

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  #port: 8080
  port: 7950
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    #host: 127.0.0.1
    host: 47.104.111.82
    # 端口，默认为6379
    port: 6379
    # 密码
    #password: 123456
    password: unified-login
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌秘钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 30

# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ruoyi.project.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  enable: true

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
gen:
  # 作者
  author: ruoyi
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.ruoyi.project.system
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_
